### PR TITLE
Ofast 98 submit page draft

### PR DESCRIPTION
**Pull request by sd0623**
Submit fields
- time limit text field
- checker dropdown and each variable has useState and shows only when respective checker is selected
- run button (no action now)

Code upload
- drag n drop zone with also select button
- folder dialog shows only accepted files when click select (.c, .cpp, .java, .py)
- for drag n drop, error check implemented for non-accepted file types or multiple files
- Code preview using MDX (prob stretch goal for code editor)

Folder upload
- drag n drop zone and select 
- folder dialog shows only .zip
- same as code upload, implemented error check for non-accepted files
- right now, after success upload -> shows zip folder name

https://github.com/ofast-team/frontend/assets/84353905/064087f5-6d13-492b-b8d3-72ae81f9235e

To do (after Judge API):
- after click run, show each test case as a box in folder upload box with response from judge
- include animation for running cases, have a loading action to let users know to not refresh the page (else lose data)
- each test case box after click shows its details: verdict, actual vs expected output

### CODE REVIEW

**Comment by gblake31** [comment]
This is super nit-picky, but could you line this up?
image
You should be able to do this with flexbox and 'justify-content: space-between'

**Comment by gblake31** [comment]
I really like the UI for this, nice work.
image

**Comment by gblake31** [comment]
Eventually, we're going to need to pass all the input data (code file, test files, checker type, etc.) up to the parent SubmitPage.tsx, so that it can have all the information when it calls the API. We can do this by passing a function down to each of the children whose job it is to update the state of the parent. We can do this later.

**Review by gblake31 — APPROVED** [review]

**Review by AsirAAlam — APPROVED** [review]
This looks great!

**Pull request merged**
