### PR TITLE
Consistent Design and Layout for both MCQ and FITB

### PR DESCRIPTION
**Pull request by sd0623**
- alignment and functionality changed and made it same for both MCQ and FITB with modular components
- just for MCQ multiple select, if user did not select all correct options, gray message is shown and for others is simple UI based
- header and verdict same design for both MCQ and FITB
- explanation and hint are optional

https://github.com/ofast-team/frontend/assets/84353905/254da9cc-cde9-4c67-9a9d-7423852e6068
https://github.com/ofast-team/frontend/assets/84353905/38ff3471-b4ea-40e9-8423-be1c50dba443

NOTE: I created this branch based on landingPage branch, so that's why there is HomeCard and HomePage changes, it is just svg file and title, which can be moved into main. Here is the screenshot of how its looking like. Still need to do animations, which will be in landingPage branch.

Screenshot 2024-02-19 at 1 30 10 AM

Other changes included mostly with CSS and tags text in `MockProblemData` was to get a better screenshot for CDR.

### CODE REVIEW

**Comment by gblake31** [comment]
When the user hits the "Show Answer" button, it seems weird to show the "Correct" banner at the bottom; they didn't get the correct answer. We don't want to reward the user too much for clicking that. However, we still want them to see the explanation at the bottom, so I wouldn't want to get rid of the banner completely. I'll still approve, and we can talk about this tomorrow.

**Comment by gblake31** [comment]
When there is no explanation provided, use a conditional to leave that part out instead of saying "no explanation provided." Just the correct banner is fine.
image

I think you should do the same thing with the hint. If no hint was provided, you should remove the lightbulb button. Otherwise, the user will expect to get a hint when they click it and be dissapointed.

**Comment by gblake31** [comment]
Thanks again for working with my code, I know the design was pretty convoluted.

**Comment by sd0623** [comment]
Made changes
- Show answer: shows only correct options and explanation, no correct banner
- Hint and explanation: shown only if provided, same with hint icon 
Screenshot 2024-02-19 at 2 23 30 PM
Screenshot 2024-02-19 at 2 23 13 PM
Screenshot 2024-02-19 at 2 22 35 PM

**Review by gblake31 — APPROVED** [review]

**Pull request merged**
