### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by sd0623**
- Full landing page
- Framer motion gear animation

https://github.com/ofast-team/frontend/assets/84353905/f344bc90-5cf0-47c4-9c16-98d20877db98

### CODE REVIEW

**Comment by gblake31** [comment]
We're using ChatGPT to generate the text right? We'll want to change this before STEM day.

**Comment by gblake31** [comment]
Nice job with the new horizontal scroll bar. I know that was tricky to do.

**Comment by sd0623** [comment]
https://github.com/ofast-team/frontend/assets/84353905/8dc6035d-3565-4c29-95bc-66406aebd4e8

**Comment by gblake31** [comment]
Awesome! I'm gonna let someone else approve since I contributed to this PR.

**Review by AsirAAlam — APPROVED** [review]
homepage looks great! minor comments.

**Pull request merged**
