### PR TITLE
OFAST-100 Search and Fetch Problems

### PR DESCRIPTION
**Pull request by AsirAAlam**
These updates are for the Solve Page. Added problem search feature and now fetching problems from MockProblemData.

- Typing into the search bar searches the mock problem archive using the problem title shows a list of search results. The problem can be clicked on to go to the problem page.
- Installed framer-motion for some subtle animation on the search result items. We will likely also use this library to improve other parts of the website.
- Before, the problems in the problem table were sourced from its own list of mock problem data. Now, the problems are fetched from the same source as the problem page content, which is MockProblemData.tsx. This file contains the mock problem data, as well as functions for retrieving problem data. If we move problem fetching to the backend, these functions will serve as a good starting point for necessary API endpoints. 
- ClickOutside is a component that detects when the user clicks outside of the component and takes a callback function. This is used to hide the search results dropdown when clicking away.
- Generated some mock problem data. Titles were generated using ChatGPT.

|Before|After|
|---|---|
|image|image|

|Search results|
|---|
|image|

https://github.com/ofast-team/frontend/assets/46213673/a06246ea-7ebe-49f2-89a7-42fc719a660c

### CODE REVIEW

**Review by gblake31 — COMMENTED** [review]
"real-time" search is an awesome feature that will put us ahead of Codeforces and Kattis for problem search. Does the search bar have the ability to modify what shows up in the table, or is it only supposed to display results in the drop-down menu?

**Comment by gblake31** [comment]
The visuals are very clean. I wouldn't change much there.

**Comment by AsirAAlam** [comment]
> "real-time" search is an awesome feature that will put us ahead of Codeforces and Kattis for problem search. Does the search bar have the ability to modify what shows up in the table, or is it only supposed to display results in the drop-down menu?

The search bar's purpose is to quickly find a problem for which you already know the title. So, it's not intended to update the table. However, for exploring new problems, there should be a separate filtering option that lets the user filter the table based on any problem meta data like title, tags, attempt status, etc.

**Comment by gblake31** [comment]
> The search bar's purpose is to quickly find a problem for which you already know the title. So, it's not intended to update the table. However, for exploring new problems, there should be a separate filtering option that lets the user filter the table based on any problem meta data like title, tags, attempt status, etc.

Makes sense. Like that's the quickest possible way to pull up a problem if you know what you want.

**Review by gblake31 — APPROVED** [review]

**Review by sd0623 — APPROVED** [review]
LGTM!

We can also use the same search bar functionality for learn and submissions page as well.

**Pull request merged**
